# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: dynamicsource
# spec:
#   selector:
#     matchLabels:
#       app: dynamicsource
#   template:
#     metadata:
#       labels:
#         app: dynamicsource
#     spec:
#       containers:
#       - name: dynamicsource
#         image: ko://github.com/triggermesh/bringyourown/sources/golang/dynamicsource
#         # gcr.io/neffdev/byo
#         env:
#         - name: EVENT_TYPE
#           value: sample.type
#         - name: EVENT_SOURCE
#           value: sample.source
#         - name: EVENT_SUBJECT
#           value: sample.subject
#         - name: EVENT_ID
#           value: sample.id
#         - name: PAYLOAD
#           value: not working
#         - name: TIMEOUT
#           value: '1000ms'
#         - name:  K_SINK
#           value: http://broker-ingress.knative-eventing.svc.cluster.local/midimansland/default

apiVersion: sources.knative.dev/v1
kind: ContainerSource
metadata:
  name: dynamicsource
spec:
  template:
    spec:
      containers:
        - image: gcr.io/neffdev/byo
          name: dynamicsource
          env:
          - name: EVENT_TYPE
            value: sample.type
          - name: EVENT_SOURCE
            value: sample.source
          - name: EVENT_SUBJECT
            value: sample.subject
          - name: EVENT_ID
            value: sample.id
          - name: PAYLOAD
            value: null
          - name: TIMEOUT
            value: '1000ms'
          - name:  SINK
            value: http://broker-ingress.knative-eventing.svc.cluster.local/midimansland/default

  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Broker
      name: default