# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: dynamicsource
# spec:
apiVersion: sources.knative.dev/v1
kind: ContainerSource
metadata:
  name: dynamicsource
spec:
  template:
    spec:
      containers:
        - image: gcr.io/neffdev/byo
          name: dynamicsource
          env:
          - name: EVENT_TYPE
            value: sample.type
          - name: EVENT_SOURCE
            value: sample.source
          - name: EVENT_SUBJECT
            value: sample.subject
          - name: EVENT_ID
            value: sample.id
          - name: PAYLOAD
            value: -|
              {"hello":"world"}
          - name: TIMEOUT
            value: '1000ms'
          - name:  SINK
            value: http://broker-ingress.knative-eventing.svc.cluster.local/midimansland/default

  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Broker
      name: default