apiVersion: sources.knative.dev/v1alpha1
kind: SinkBinding
metadata:
  name: bind-google-storage
spec:
  subject:
    apiVersion: apps/v1
    kind: Deployment
    name: googlecloudstorage

  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: sockeye
  ceOverrides:
    extensions:
      sink: bound
